version: '2'
services:
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    volumes:
      - ../:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/logs:cached
    links:
      - db
  nginx:
    build: nginx
    ports:
      - '80:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc
      MYSQL_USER: igor
      MYSQL_PASSWORD: igor
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
        - "8080:80"